name: Code Quality Check

permissions:
  contents: read

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    name: Format and Lint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v3
        with:
          version: "0.12.7"
      - uses: chartboost/ruff-action@v3
        with:
          version: "0.12.7"
          args: 'format --check'
